version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
      - chroma

  frontend:
    build:
      context: ./frontend/web-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: orchestrator

  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8001"
